<?php if ( $block->isAvailable() ) : ?>

<script type="text/javascript">
	require(["jquery"], function (e) {
	    var i = "playground" === window.pacePayEnvironment ? "pacePayPlayground" : "pacePay",
	        t = window.pacePaymentPlan;
	    if (null !== t.paymentPlans && t.paymentPlans.isAvailable) {
	        var a = t.paymentPlans;
	        require([i], function (i) {
	            var t = i.init({
	                    fallbackWidget: window.pacePayBaseWidgetConfig.fallbackWidget,
	                    currency: a.currencyCode,
	                    minAmount: parseFloat(a.minAmount.actualValue),
	                    maxAmount: parseFloat(a.maxAmount.actualValue),
	                    styles: window.pacePayBaseWidgetConfig.styles ? window.pacePayBaseWidgetConfig.styles : void 0,
	                }),
	                n = {
	                    init: function (i) {
	                        window.pacePayBaseWidgetConfig && window.pacePayBaseWidgetConfig.baseActive && (this.singleWidget(i), this.catalogWidget(i)),
	                            e(document.body).on("updatePrice", function (t, a) {
	                                if (void 0 !== a && a.hasOwnProperty("prices")) {
	                                    var o = e(document.body).find(".pace-pay_single-product-widget-container");
	                                    if (o.length) {
	                                        var d = parseFloat(a.prices.finalPrice.amount),
	                                            c = e(document.body).find('span[data-price-type="finalPrice"]');
	                                        c.length && (d += parseFloat(c.attr("data-price-amount"))), o.attr("data-price", d), n.singleWidget(i);
	                                    }
	                                }
	                            });
	                    },
	                    singleWidget: function (e) {
	                        window.pacePaySingleProductWidgetConfig.isActive &&
	                            e.loadWidgets({
	                                containerSelector: ".pace-pay_single-product-widget-container",
	                                type: "single-product",
	                                styles: window.pacePaySingleProductWidgetConfig.styles ? window.pacePaySingleProductWidgetConfig.styles : void 0,
	                            });
	                    },
	                    catalogWidget: function (e) {
	                        window.pacePayMultiProductsWidgetConfig.isActive &&
	                            e.loadWidgets({
	                                containerSelector: ".pace-pay_multi-products-widget-container",
	                                type: "multi-products",
	                                styles: window.pacePayMultiProductsWidgetConfig.styles ? window.pacePayMultiProductsWidgetConfig.styles : void 0,
	                            });
	                    },
	                };
	            n.init(t), (window.pacePay = t);
	        });
	    }
	});
</script>

<?php endif; ?>