<?php if ( $block->isAvailable() ) : ?>

<script type="text/javascript">
require(["jquery"], function (e) {
    var i = "playground" === window.pacePayEnvironment ? "pacePayPlayground" : "pacePay",
        a = window.pacePaymentPlan;
    if (null !== a.paymentPlans && a.paymentPlans.isAvailable) {
        var t = a.paymentPlans;
        require([i], function (i) {
            var a = i.init({
                    fallbackWidget: window.pacePayBaseWidgetConfig.fallbackWidget,
                    currency: t.currencyCode,
                    minAmount: parseFloat(t.minAmount.actualValue),
                    maxAmount: parseFloat(t.maxAmount.actualValue),
                    styles: window.pacePayBaseWidgetConfig.styles ? window.pacePayBaseWidgetConfig.styles : void 0,
                }),
                n = {
                    init: function (i) {
                        window.pacePayBaseWidgetConfig && window.pacePayBaseWidgetConfig.baseActive && (this.singleWidget(i), this.catalogWidget(i)),
                            e(document.body).on("updatePrice", function (a, t) {
                                if (void 0 !== t && t.hasOwnProperty("prices")) {
                                    var o = e(document.body).find(".pace-pay_single-product-widget-container");
                                    if (o.length) {
                                        var d = parseFloat(t.prices.finalPrice.amount),
                                            c = e(document.body).find('span[data-price-type="finalPrice"]');
                                        c.length && (d += parseFloat(c.attr("data-price-amount"))), o.attr("data-price", d), n.singleWidget(i);
                                    }
                                }
                            });
                    },
                    singleWidget: function (e) {
                        var i = jQuery(".pace-pay_single-product-widget-container");
                        window.pacePaySingleProductWidgetConfig.isActive &&
                            i.length &&
                            1 != i.data("blacklisted") &&
                            e.loadWidgets({
                                containerSelector: ".pace-pay_single-product-widget-container",
                                type: "single-product",
                                styles: window.pacePaySingleProductWidgetConfig.styles ? window.pacePaySingleProductWidgetConfig.styles : void 0,
                            });
                    },
                    catalogWidget: function (e) {
                        window.pacePayMultiProductsWidgetConfig.isActive &&
                            e.loadWidgets({
                                containerSelector: ".pace-pay_multi-products-widget-container",
                                type: "multi-products",
                                styles: window.pacePayMultiProductsWidgetConfig.styles ? window.pacePayMultiProductsWidgetConfig.styles : void 0,
                            });
                    },
                };
            n.init(a), (window.pacePay = a);
        });
    }
});
</script>

<?php endif; ?>