filter_on_master: &filter_on_master
  filters:
    branches:
      only: master

version: 2.1
jobs:
  publish_to_git:
    working_directory: ~/repo/internal
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          git config --global user.name "Pace Robot"
          git config --global user.email "merchant-integration@pacenow.co"
          git config --list
      - run: pwd

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_on_master
