filter_on_master: &filter_on_master
  filters:
    branches:
      only: master

version: 2.1
jobs:
  publish_to_git:
    working_directory: ~/repo/internal
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          cd ~/repo
          pwd
          git config --global user.name "Pace Robot"
          git config --global user.email "merchant-integration@pacenow.co"
          git config --list
          git clone git@github.com:PaceNow/pace-for-magento-2.git
          ls pace-for-magento-2

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_on_master
