filter_on_master: &filter_on_master
  filters:
    branches:
      only: master

version: 2.1
jobs:
  publish_to_git:
    working_directory: ~/repo
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: |
          git config --global user.name "Pace Robot"
          git config --global user.email "merchant-integration@pacenow.co"
          git config --list
          echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> ~/.ssh/known_hosts
          git clone git@github.com:PaceNow/pace-for-magento-2.git
      - run: pwd
      - run: ls

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_on_master
