filter_tags: &filter_tags
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^v.*/

version: 2.1
jobs:
  publish_to_git:
    working_directory: ~/repo/internal
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          tag=$(git describe --abbrev=0 --tags)
          cd ~/repo
          git config --global user.name "Pace Robot"
          git config --global user.email "merchant-integration@pacenow.co"
          git clone git@github.com:PaceNow/pace-for-magento-2.git
          cd pace-for-magento-2
          git remote add internal git@github.com:PaceNow/pace-for-magento-2-internal.git
          git remote update
          git merge --allow-unrelated-histories --squash -X theirs $tag
          ./internal/generateReadme.sh $tag
          ./internal/generateComposer.sh ${tag/v}
          git reset -- internal
          git reset -- .circleci
          git add README.md
          git add composer.json
          git commit -m $tag
          git push
          git push origin $tag

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_tags
