filter_on_master: &filter_on_master
  filters:
    branches:
      only: master

version: 2.1
jobs:
  publish_to_git:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - run: git config --list

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_on_master
