filter_on_master: &filter_on_master
  filters:
    branches:
      only: master

version: 2.1
jobs:
  publish_to_git:
    working_directory: ~/repo/internal
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: |
          tag=$(git describe --tag)
          cd ~/repo
          pwd
          git config --global user.name "Pace Robot"
          git config --global user.email "merchant-integration@pacenow.co"
          git config --list
          git clone git@github.com:PaceNow/pace-for-magento-2.git
          cd pace-for-magento-2
          git remote add internal git@github.com:PaceNow/pace-for-magento-2-internal.git
          git remote update
          git merge --allow-unrelated-histories --squash -X theirs $tag
          echo $tag
          git commit -m $tag
          ls
          git log
          git status

workflows:
  version: 2
  build:
    jobs:
      - publish_to_git:
          <<: *filter_on_master
