<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery) {
        jQuery('#payment-plan_refresh-button').click(function() {
            params = {
                form_key: '<?php echo $block->getFormKey() ?>',
                isAjax: true
            };
            // Make the ajax call and handel data.
            jQuery.ajax({
                showLoader: true,
                url: "<? echo $block->getAjaxUrl() ?>",
                data: params,
                dataType: 'json'
            }).done(function(data) {
                var paymentPlan = data.paymentPlan;
                var id = paymentPlan.id;
                var currencyCode = paymentPlan.currencyCode;
                var maxAmount = paymentPlan.maxAmount.actualValue;
                var minAmount = paymentPlan.minAmount.actualValue;

                jQuery('#payment-plan_id').text(id);
                jQuery('#payment-plan_currency').text(currencyCode);
                jQuery('#payment-plan_min-amount').text(minAmount);
                jQuery('#payment-plan_max-amount').text(maxAmount);
            });
        });
    });
</script>

<?php $paymentPlan = $block->getPaymentPlan() ?>

<?php if (isset($paymentPlan)) : ?>
    <table style="margin-bottom: 16px;">
        <tr>
            <td>ID</td>
            <td id="payment-plan_id">
                <? echo $paymentPlan['id'] ?>
            </td>
        </tr>
        <tr>
            <td>Currency</td>
            <td id="payment-plan_currency">
                <? echo $paymentPlan['currency'] ?>
            </td>
        </tr>
        <tr>
            <td>Min Amount</td>
            <td id="payment-plan_min-amount">
                <? echo $paymentPlan['minAmount'] ?>
            </td>
        </tr>
        <tr>
            <td>Max Amount</td>
            <td id="payment-plan_max-amount">
                <? echo $paymentPlan['maxAmount'] ?>
            </td>
        </tr>
    </table>
<?php else : ?>
    <div>
        <p>No available payment plan.</p>
    </div>
<?php endif; ?>