<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery) {
        jQuery('#payment-plan_refresh-button').click(function() {
            params = {
                form_key: '<?php echo $block->getFormKey() ?>',
                isAjax: true
            };
            // Make the ajax call and handel data.
            jQuery.ajax({
                showLoader: true,
                url: "<? echo $block->getAjaxUrl() ?>",
                data: params,
                dataType: 'json'
            }).done(function(data) {
                var paymentPlan = data.paymentPlan;
                var id = paymentPlan.id;
                var currencyCode = paymentPlan.currencyCode;
                var maxAmount = paymentPlan.maxAmount.actualValue;
                var minAmount = paymentPlan.minAmount.actualValue;

                jQuery('#payment-plan_id').text(id);
                jQuery('#payment-plan_currency').text(currencyCode);
                jQuery('#payment-plan_min-amount').text(minAmount);
                jQuery('#payment-plan_max-amount').text(maxAmount);
            });
        });
    });
</script>

<table style="margin-bottom: 16px;">
    <tr>
        <td>ID</td>
        <td id="payment-plan_id">
            <? echo $block->getPaymentPlanId() ?>
        </td>
    </tr>
    <tr>
        <td>Currency</td>
        <td id="payment-plan_currency">
            <? echo $block->getPaymentPlanCurrency() ?>
        </td>
    </tr>
    <tr>
        <td>Min Amount</td>
        <td id="payment-plan_min-amount">
            <? echo $block->getPaymentPlanMin() ?>
        </td>
    </tr>
    <tr>
        <td>Max Amount</td>
        <td id="payment-plan_max-amount">
            <? echo $block->getPaymentPlanMax() ?>
        </td>
    </tr>
</table>
<?php
// $controller = $block->getCustomUrl();
echo $block->getButtonHtml();
?>