<?php
    $paymentPlan = $block->getPaymentPlan();

    if (isset($paymentPlan['paymentPlans']) && !empty($paymentPlan['paymentPlans'])) {
        $paymentPlan = $paymentPlan['paymentPlans'];

        echo "
            <table style=\"margin-bottom: 16px;\">
                <tr>
                    <td>ID</td>
                    <td>{$paymentPlan->id}</td>
                </tr>
                <tr>
                    <td>Currency</td>
                    <td>{$paymentPlan->currencyCode}</td>
                </tr>
                <tr>
                    <td>Min Amount</td>
                    <td>{$paymentPlan->displayMinAmount}</td>
                </tr>
                <tr>
                    <td>Max Amount</td>
                    <td>{$paymentPlan->displayMaxAmount}</td>
                </tr>
            </table>
        ";
    } else {
        echo "<p class=\"note\"><span>{$paymentPlan}</span></p>";
    }